name: apk produccion
on:
 push:
  branches: [ master ]
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup Java JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Build Debug APK
      run: ./gradlew assembleRelease
      
    - name: List artifact APK
      run: ls -la
      
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.1
      with:
        name: app-debug.apk
        path: ./app/build/outputs/apk/release
        
    - name: Build Signed APK
      uses: victorbnl/build-signed-apk@v1.0.0
      with:
       keystore: keymoviuq
    # Keystore file password
       keystore_password: moviuq2022
    # Key alias
       key_alias: keymoviuq
    # Key password
       key_password: moviuq2022
      
   
